{% set name = "spectrafit" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spectrafit-{{ version }}.tar.gz
  sha256: 2767a78324eb2e39ff1089b7e2ee37a50ae368ab0fc4a38fc9bf12594db1036c

build:
  noarch: python
  number: 2
  entry_points:
        - spectrafit = spectrafit.spectrafit:command_line_runner
        - spectrafit-converter = spectrafit.plugins.converter:command_line_runner
        - spectrafit-jupyter = spectrafit.app.app:jupyter


requirements:
  host:
    - pip
    - python >=3.7,<3.11
    # - poetry >=1.1,<1.2
  run:
    - python >=3.7,<3.11
    - pyyaml >=6.0,<7.0
    - ascii-art >=5.7,<6.0
    - emcee >=3.1.2,<4.0.0
    - lmfit >=1.0.3,<2.0.0
    - numdifftools >=0.9.39,<0.10.0
    - openpyxl >=3.0.9,<4.0.0
    - pydantic >=1.10.1,<2.0.0
    - scikit-learn >=1.0.2,<2.0.0
    - seaborn >=0.11.2,<0.12.0
    - tabulate >=0.8.10,<0.10.0
    - tomli-w >=1.0.0,<2.0.0
    - tomli >=2.0.1,<3.0.0
    - tqdm >=4.64.0,<5.0.0
    - pandas >=1.3.5,<2.0.0
    - numpy >=1.21.6,<2.0.0
    - pydantic >=1.10.1,<2.0.0
    - jupyterlab >=3.4.5,<4.0.0
    - python-kaleido ==0.2.1
    - itables >=1.3.0,<2.0.0
    - plotly >=5.10.0,<6.0.0
    - dtale >=2.8.1,<3.0.0
test:
  imports:
    - spectrafit
  commands:
    - spectrafit --help
    - spectrafit-converter --help
    - spectrafit-jupyter --help
    - python -c "from spectrafit.plugins.notebook import SpectraFitNotebook"

about:
  home: https://pypi.org/project/spectrafit/
  summary: Fast fitting of 2D-Spectra with established routines
  description: |
    SpectraFit is a command-line and Jupyter-notebook tool for
    quick data-fitting based on the regular expression of
    distribution functions.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://anselmoo.github.io/spectrafit/
  dev_url: https://github.com/anselmoo/spectrafit

extra:
  recipe-maintainers:
    - Anselmoo
